do_train: true
do_valid: false
do_test: 
evaluate_train: 
countries: 
regions: 
data_path: 
model: 
double_entity_embedding: 
double_relation_embedding: 
negative_sample_size: 
hidden_dim: 
gamma: 
negative_adversarial_sampling: 
adversarial_temperature: 
batch_size: 
regularization: 
test_batch_size: 
uni_weight: 
learning_rate: 
cpu_num: 
init_checkpoint: 
save_path: 
max_steps: 
warm_up_steps: 
save_checkpoint_steps: 
valid_steps: 
log_steps: 
test_log_steps: 
nentity: 
nrelation: 
autoencoder_flag: 
autoencoder_hidden_dim: 
autoencoder_lambda: 
wandb_project: 
track: 
saving_metric: 
saving_threshold: 
random_seed: 
timestamp: 
saved_config_path: 
