# -------------------- General Parameters --------------------
seed: 42
epochs: 10
batch_size: 128
val_every_n_batches: 50
num_warmup_steps: 300
    
# -------------------- General Data Parameters --------------------
path_mquake_data: "./data/mquake/"
tvt_split: [0.8, 0.1, 0.1]
path_graph_emb_data: "./models/graph_embeddings/transE_mquake_dim500"
outPath_save_model: "./models/gtllm/"

# -------------------- Language Modeling Parameters --------------------
hunchbart_base_llm_tokenizer: "facebook/bart-base"
hunchbart_base_llm_model: "facebook/bart-base"
baseline_lr: 0.001
minimum_lr: 0.000001
